// Code generated by goctl. DO NOT EDIT.
package types

type GetIndexDataReq struct {
}

type GetIndexDataRes struct {
	Status int64               `json:"status"`
	Msg    string              `json:"msg"`
	Data   GetIndexDataResData `json:"data"`
}

type GetIndexDataResData struct {
	GamerCount   int64 `json:"gamerCount"`
	ChallengeNum int64 `json:"challengeNum"`
	BestScore    int64 `json:"bestScore"`
	BestRank     int64 `json:"bestRank"`
}

type GetRankListReq struct {
	Page int64 `form:"page"`
	Size int64 `form:"size"`
}

type GetRankListRes struct {
	Status int64                `json:"status"`
	Msg    string               `json:"msg"`
	Data   []GetRankListResData `json:"data"`
	Count  int64                `json:"count"`
}

type GetRankListResData struct {
	HeadUrl  string `json:"headUrl"`
	UserName string `json:"userName"`
	UserAge  int64  `json:"userAge"`
	Score    int64  `json:"score"`
}

type SendGameInfoReq struct {
	Score int64 `json:"score"`
}

type SendGameInfoRes struct {
	Status int64  `json:"status"`
	Msg    string `json:"msg"`
}

type SendUserInfoReq struct {
	ChallengeId int64  `json:"challengeId"`
	AccountName string `json:"accountName"`
	AccountPass string `json:"accountPass"`
	UserName    string `json:"userName"`
	UserAge     int64  `json:"userAge"`
	UserHeadUrl string `json:"userHeadUrl"`
}

type SendUserInfoRes struct {
	Status int64               `json:"status"`
	Msg    string              `json:"msg"`
	Data   SendUserInfoResData `json:"data"`
}

type SendUserInfoResData struct {
	Token string `json:"token"`
}
