// Code generated by goctl. DO NOT EDIT.

package challenge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	challengeFieldNames          = builder.RawFieldNames(&Challenge{})
	challengeRows                = strings.Join(challengeFieldNames, ",")
	challengeRowsExpectAutoSet   = strings.Join(stringx.Remove(challengeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	challengeRowsWithPlaceHolder = strings.Join(stringx.Remove(challengeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	challengeModel interface {
		Insert(ctx context.Context, data *Challenge) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Challenge, error)
		Update(ctx context.Context, data *Challenge) error
		Delete(ctx context.Context, id int64) error
	}

	defaultChallengeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Challenge struct {
		Id        int64         `db:"id"`
		GameId    sql.NullInt64 `db:"gameId"`
		GameLevel sql.NullInt64 `db:"gameLevel"`
		EntTime   sql.NullInt64 `db:"entTime"`
	}
)

func newChallengeModel(conn sqlx.SqlConn) *defaultChallengeModel {
	return &defaultChallengeModel{
		conn:  conn,
		table: "`challenge`",
	}
}

func (m *defaultChallengeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChallengeModel) FindOne(ctx context.Context, id int64) (*Challenge, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", challengeRows, m.table)
	var resp Challenge
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChallengeModel) Insert(ctx context.Context, data *Challenge) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, challengeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.GameId, data.GameLevel, data.EntTime)
	return ret, err
}

func (m *defaultChallengeModel) Update(ctx context.Context, data *Challenge) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, challengeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.GameId, data.GameLevel, data.EntTime, data.Id)
	return err
}

func (m *defaultChallengeModel) tableName() string {
	return m.table
}
