// Code generated by goctl. DO NOT EDIT.

package game

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameFieldNames          = builder.RawFieldNames(&Game{})
	gameRows                = strings.Join(gameFieldNames, ",")
	gameRowsExpectAutoSet   = strings.Join(stringx.Remove(gameFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameRowsWithPlaceHolder = strings.Join(stringx.Remove(gameFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gameModel interface {
		Insert(ctx context.Context, data *Game) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Game, error)
		Update(ctx context.Context, data *Game) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGameModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Game struct {
		Id           int64         `db:"id"`
		GameId       int64         `db:"gameId"`
		GameName     string        `db:"gameName"`
		GameMaxLevel sql.NullInt64 `db:"gameMaxLevel"`
	}
)

func newGameModel(conn sqlx.SqlConn) *defaultGameModel {
	return &defaultGameModel{
		conn:  conn,
		table: "`game`",
	}
}

func (m *defaultGameModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGameModel) FindOne(ctx context.Context, id int64) (*Game, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameRows, m.table)
	var resp Game
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameModel) Insert(ctx context.Context, data *Game) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, gameRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.GameId, data.GameName, data.GameMaxLevel)
	return ret, err
}

func (m *defaultGameModel) Update(ctx context.Context, data *Game) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.GameId, data.GameName, data.GameMaxLevel, data.Id)
	return err
}

func (m *defaultGameModel) tableName() string {
	return m.table
}
